### ISSUE TITLE
Life360 and Hassio 0.74.2

### ISSUE THREAD

**Issue by neonclear** [editter/hassio-addons#5]
First off, thank you so much for developing this. This has been a real life changer. I upgraded to Hassio 0.74.2 and the Life360 Add-On has stopped working. It seems to connect to Life360 but is unable to update MQTT. Here's what happens when I start it up.

`starting version 3.2.4
7/31 9:59:21 am - info: init/refresh token successful
7/31 9:59:21 am - info: Configuring auto update for every 1 minutes
7/31 9:59:22 am - info: Configuring server
7/31 9:59:22 am - info: Listing via https
7/31 9:59:22 am - info: Listening at port 8081
7/31 9:59:22 am - info: HTTP Message sent for b_phone
7/31 9:59:22 am - info: HTTP Message sent for s_phone
7/31 9:59:22 am - info: Circle 1 of 1: L Family
7/31 9:59:22 am - info: Member 1 of 2
 Name: B; Data: {
    "dev_id": "b_phone",
    "gps": [
        **.************,
        -**.************
    ],
    "gps_accuracy": 65,
    "battery": 84,
    "attributes": {
        "speed": -1,
        "is_driving": 0,
        "is_intransit": 0,
        "is_charging": 0,
        "wifi_state": 1,
        "address1": "Atomic",
        "address2": ""
    }
} 
7/31 9:59:22 am - info: Member 2 of 2
 Name: S; Data: {
    "dev_id": "s_phone",
    "gps": [
        **.************,
        -**.************
    ],
    "gps_accuracy": 65,
    "battery": 29,
    "attributes": {
        "speed": -1,
        "is_driving": 0,
        "is_intransit": 0,
        "is_charging": 0,
        "wifi_state": 1,
        "address1": "Home",
        "address2": ""
    }
} 
7/31 9:59:22 am - error:  Error: Request failed with status code 401
    at createError (/life360/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/life360/node_modules/axios/lib/core/settle.js:18:12)
    at IncomingMessage.handleStreamEnd (/life360/node_modules/axios/lib/adapters/http.js:192:11)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
7/31 9:59:22 am - error:  Error: Request failed with status code 401
    at createError (/life360/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/life360/node_modules/axios/lib/core/settle.js:18:12)
    at IncomingMessage.handleStreamEnd (/life360/node_modules/axios/lib/adapters/http.js:192:11)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)`

The same error will just keep repeating forever.

Here's a better file of the log because I'm no master of github
[life360 log.txt](https://github.com/editter/hassio-addons/files/2245581/life360.log.txt)

**Comment by editter** [comment]
I remember hearing something about an update coming to Hassio add-ons which may be the issue.  Let me take a look tonight and I will see what I can do.

**Comment by HIT2022** [comment]
Any luck with this @editter? I haven't had a chance to test the API to see if anything changed on their end, but my device_tracker hasn't been getting set via HTTP for a few weeks now.

Thanks again for supporting it.

**Comment by editter** [comment]
I did take a look and I wasn't able to find anything. I did post in the community to see if anyone had an answer but no one has responded. It seems like a basic problem but I keep getting a 401 error and it says API request not allowed.

**Comment by HITChris** [comment]
I can get around the 401 on my local build by using the API password ('x-ha-access': 'whatever'). Not sure what has changed with how the API handles proxy authorization (via X-HASSIO-KEY), but that set to the value from environment variable HASSIO_TOKEN no longer seems to work for internal communication. Looks like this commit might be related - https://github.com/home-assistant/hassio/pull/633

**Comment by HIT2022** [comment]
Not sure what has changed with how the Hass.io API handles authorization, but X-HASSIO-KEY set to the value from environment variable HASSIO_TOKEN no longer seems to work for internal communication. Commit home-assistant/hassio#633 might be related?

**Comment by editter** [comment]
I have been looking at this again but with no luck.  I am able to go from HA to an HA Addon via the API but not the other way around so I may not be using things correctly.  I will be making some changes to this tonight.  What version of HA are you using?

**Comment by editter** [comment]
I think I was able to resolve this by updating the base image of the addon but that took more work than I would have thought.  I will be pushing out a fix for this later tonight, again sorry for the delay.

**Comment by editter** [comment]
Sorry for the delays in getting this resolved but I think version 0.13 should resolve it.  If you have any issues please let me know and I will do what I can, thanks for letting me know.

**Comment by HIT2022** [comment]
Thanks @editter. So the API fix was just moving from 'X-HASSIO-KEY' to 'x-ha-access'/'content-type'? Do you know what HA auth change this break/fix ties back to? I spent a good deal of time on this a few weeks back and 'x-ha-access' was one of the variations I tried, but I didn't include 'content-type' (assuming application/json to be the default) so that might be why it was giving me difficulty. Also, with HA's moving to a new authorization platform, do you know if any changes will need to be made to this add-on to support oauth2?

**Comment by editter** [comment]
I don't think the content type was the issue but while I was working on fixing it I added that in and ended up leaving it there because it doesn't hurt. If I remember right I tried a bunch of variations and nothing fixed it until the previous release. So the original issue was that I didn't use the newer hassio header but the fix was delayed due to a bug somewhere in HA.  

I am not sure how the auth system will affect it but my initial thought is that local apps won't be affected, at least initially, because the value that is set in the environment variable is system generated anyway (might be a refresh token from the hassio user actually, but again is hassio managed).

If you hear anything different please let know. I try to keep up on changes coming but this project moves pretty quick so I miss a decent amount  :)
